### ISSUE TITLE
Rewards charts Max different on App Explorer, App homepage and web explorer 

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#115]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:

- Android Application

## **Describe the bug**

The rewards chart section in the Android app under the Weather station homepage for "Boiling Vanilla Spring" shows max 7 day rewards as 29.07 and 30d as 87.21.

The Android app Explorer for the same station shows max as 29.08 and 87.22.

The website based Explorer shows 29.07 and 87.22.

### **How To Reproduce**
1. Compare the 7d and 30d max charts for Boiling Vanilla Spring in the Android app station homepage, the Android app Explorer and the web based Explorer.

### **Expected behavior**
All graphs should be consistent.

### **Screenshots**
![Screenshot_20220728-125933.png](https://user-images.githubusercontent.com/100298772/181628157-99031ff5-c0aa-42ac-a2e9-cd483b4febe0.png)

![Screenshot_20220728-130000.png](https://user-images.githubusercontent.com/100298772/181628173-9314ea25-55f2-4f10-8992-22eaf560d3ef.png)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**
 - Device: [Google Pixel 2 
 - OS: Android 11 
 - Browser [Chrome]
 - Android App Version 3.1.3-2f401de

**Comment by Skallagrimmm** [comment]
Also the 7d and 3d totals appear to be off by a few decimal points.

**Comment by PavlosTze** [comment]
@Skallagrimmm The different number in-app have been fixed in the latest beta release. The difference with the Web Explorer (or the Web App) should still be there on some situations (it's a rounding issue) but as also mentioned [here](https://github.com/WeatherXM/issue-tracker/issues/107) we will probably go with a different solution in the future to catch and fix all those small rounding issues.

Therefore I am closing this issue as fixed on the Android. :)
