### ISSUE TITLE
Easier way to copy your station name

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#149]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:

- Android Application
- iOS Application
- Web App

### **Is your feature request related to a problem? Please describe.**

There is no way to copy your 3 word station name, and if you have given your station a nickname, you have to clear the nickname for the original station name to appear and then wait 10 mins to re-type the nickname.

### **Describe the solution you'd like**

A hold down copy option on the station's name in each station home page, (similar to what you have done with the app version in Settings).

![Screenshot_20221105-221210.png](https://user-images.githubusercontent.com/100298772/200155488-4bb8ed1d-0e9a-4834-80cd-be2edc8d0983.png)

Alternatively, an option to copy the station's name when you go into the edit name option.

This would prevent anyone from having to delete their nickname when trying to remember and or copy and paste their station name either for diagnostic or other purposes. Would make the process of obtaining your station name two clicks instead of an annoyance.

### **Describe alternatives you've considered**

Having the station name and Nickname swap back and forth when clicked.

### **Additional context**

This is probably only an issue for people that have 2 or more stations but I assume that population is going to be growing soon.

**Comment by Greg15** [comment]
I agree with this

**Comment by Skallagrimmm** [comment]
> @Skallagrimmm and @Greg15 What do you think would be a usecase for this? We thought about it and another idea that came up was to add in the device's menu something like "Share Device Debug Info" where we could open the email app for example with pre-filled the body containing the device's info in case someone needs support.
> 
> What do you think of that?

The scenarios I was thinking of were

A. Station Owner is having some sort of issue or significant data event and wants to quote the station name to send in an email to support, create as GitHub entry or post to Discord.

B. Station Owner wants to send the names of their station to friend or family for person reason (to follow in the app).

I think that the option you suggested would meet the needs I thought about, if the owner wants to send the name or serial or whatever else info you include on the email we can always copy it and discard the email to send via a different platform

**Comment by Greg15** [comment]
My primary use cases are to 1) reduce the friction to get technical support and 2) to submit GitHub bugs.

For use case number one, "send debug info" makes a lot of sense when needing deep technical support, in which it would attempt to send an email, especially if the debug info includes a file.
For use case number two, "copy support info to clipboard" would be much more streamlined. That makes it much easier to paste it into GitHub.
There is a variation of use case #1 where the user is getting basic technical support (rather than deep technical support) from either the core team (possibly through Discord DMs) or from the discord community. At some point, I could even see a "technical support" discord channel if the need arises. 

One of the nuances is whether info is needed about just the one station the user is looking at (especially if they are on the Station Details page), or info about all stations in the account (especially if they are on the Home Page). It already helps that the software can already tell if the user initiated the function from the station details page context menu (that has Edit Name and Settings) vs the home page menu (that has Connect Wallet and Settings).

Even from the home page though, the user might need to share info only about one station.

So one approach could be a menu item added to the home page menu (that already has Connect Wallet and Settings) that does this:
Labeled something like "Share Support Info".
It then asks you to select between "All Stations" or a single station selection, where All Stations is selected by default when launched from this location.
It also asks you to choose between "Basic Info" (default) and "Include Debug File".
And it asks you to choose between "Copy to clipboard" and "Send email", where Copy to Clipboard is the default, but gets deselected and disabled if/when "Include Debug File" is selected by the user.

A similar menu item could also be available from the context menu of the Station Details page. The difference would be that by default, that specific station would be selected rather than All Stations being selected by default.

For the use case of sharing the station with others, right now what would work best for me is to have a separate menu item in the context menu to copy to the clipboard the URL that can be used to see the specific station in the explorer. Instead, I've been needing to navigate to the web explorer, click on the cell, click on the station, and copy the URL. But the reason I'm a little hesitant to request that it be added as a built in copy-to-clipboard function in the app is because I believe the URL is constructed by using the H3 resolution 7 hex ID as the subdirectory followed by a unique identifier of the station for a Sub sub directory. Which means the link might not work once if the station is moved. But as long as that scenario is handled reasonably gracefully in the explorer if someone uses a link to ask for an H3 cell and station combo that doesn't exist, then such a menu item in the app would be awesome.

Having said all of the above...
The added features, especially a feature to copy all support info to the clipboard so I can paste into Discord, would help me. I've posted 50+ or so GitHub entries. And, I'll possibly post 50+ more eventually. So it would help me. But it would potentially take more time for a developer to code it than the time it will save for me and others that have submitted the majority of the bugs so far. So I suspect the real value would be derived probably not from saving time, but from these 2 things:
1. Ensuring WeatherXM have all the info they need to address an issue and provide support, and
2. Reducing the friction for less involved or less technically capable folks to submit bugs or get technical help. That could widen the circle of folks that provide actionable info that can evolve the deployment side of the project.

**Comment by Greg15** [comment]
My primary use cases are to 1) reduce the friction to get technical support and 2) to submit GitHub bugs.

For use case number one, "send debug info" makes a lot of sense when needing deep technical support, in which it would attempt to send an email, especially if the debug info includes a file.
For use case number two, "copy support info to clipboard" would be much more streamlined. That makes it much easier to paste it into GitHub.
There is a variation of use case #1 where the user is getting basic technical support (rather than deep technical support) from either the core team (possibly through Discord DMs) or from the discord community. At some point, I could even see a "technical support" discord channel if the need arises. 

One of the nuances is whether info is needed about just the one station the user is looking at (especially if they are on the Station Details page), or info about all stations in the account (especially if they are on the Home Page). It already helps that the software can already tell if the user initiated the function from the station details page context menu (that has Edit Name and Settings) vs the home page menu (that has Connect Wallet and Settings).

Even from the home page though, the user might need to share info only about one station.

So one approach could be a menu item added to the home page menu (that already has Connect Wallet and Settings) that does this:
Labeled something like "Share Support Info".
It then asks you to select between "All Stations" or a single station selection, where All Stations is selected by default when launched from this location.
It also asks you to choose between "Basic Info" (default) and "Include Debug File".
And it asks you to choose between "Copy to clipboard" and "Send email", where Copy to Clipboard is the default, but gets deselected and disabled if/when "Include Debug File" is selected by the user.

A similar menu item could also be available from the context menu of the Station Details page. The difference would be that by default, that specific station would be selected rather than All Stations being selected by default.

For the use case of sharing the station with others, right now what would work best for me is to have a separate menu item in the context menu to copy to the clipboard the URL that can be used to see the specific station in the explorer. Instead, I've been needing to navigate to the web explorer, click on the cell, click on the station, and copy the URL. But the reason I'm a little hesitant to request that it be added as a built in copy-to-clipboard function in the app is because I believe the URL is constructed by using the H3 resolution 7 hex ID as the subdirectory followed by a unique identifier of the station for a Sub sub directory. Which means the link might not work once if the station is moved. But as long as that scenario is handled reasonably gracefully in the explorer if someone uses a link to ask for an H3 cell and station combo that doesn't exist, then such a menu item in the app would be awesome.

Having said all of the above...
The added features, especially a feature to copy all support info to the clipboard so I can paste into Discord, would help me. I've posted 50+ or so GitHub entries. And, I'll possibly post 50+ more eventually. So it would help me. But it would potentially take more time for a developer to code it than the time it will save for me and others that have submitted the majority of the bugs so far. So I suspect the real value would be derived probably not from saving time, but from these 2 things:
1. Ensuring WeatherXM have all the info they need to address an issue and provide support, and
2. Reducing the friction for less involved or less technically capable folks to submit bugs or get technical help. That could widen the circle of folks that provide actionable info that can evolve the deployment side of the project.

**Comment by Greg15** [comment]
My primary use cases are to 1) reduce the friction to get technical support and 2) to submit GitHub bugs.

For use case number one, "send debug info" makes a lot of sense when needing deep technical support, in which it would attempt to send an email, especially if the debug info includes a file.
For use case number two, "copy support info to clipboard" would be much more streamlined. That makes it much easier to paste it into GitHub.
There is a variation of use case #1 where the user is getting basic technical support (rather than deep technical support) from either the core team (possibly through Discord DMs) or from the discord community. At some point, I could even see a "technical support" discord channel if the need arises. 

One of the nuances is whether info is needed about just the one station the user is looking at (especially if they are on the Station Details page), or info about all stations in the account (especially if they are on the Home Page). It already helps that the software can already tell if the user initiated the function from the station details page context menu (that has Edit Name and Settings) vs the home page menu (that has Connect Wallet and Settings).

Even from the home page though, the user might need to share info only about one station.

So one approach could be a menu item added to the home page menu (that already has Connect Wallet and Settings) that does this:
Labeled something like "Share Support Info".
It then asks you to select between "All Stations" or a single station selection, where All Stations is selected by default when launched from this location.
It also asks you to choose between "Basic Info" (default) and "Include Debug File".
And it asks you to choose between "Copy to clipboard" and "Send email", where Copy to Clipboard is the default, but gets deselected and disabled if/when "Include Debug File" is selected by the user.

A similar menu item could also be available from the context menu of the Station Details page. The difference would be that by default, that specific station would be selected rather than All Stations being selected by default.

For the use case of sharing the station with others, right now what would work best for me is to have a separate menu item in the context menu to copy to the clipboard the URL that can be used to see the specific station in the explorer. Instead, I've been needing to navigate to the web explorer, click on the cell, click on the station, and copy the URL. But the reason I'm a little hesitant to request that it be added as a built in copy-to-clipboard function in the app is because I believe the URL is constructed by using the H3 resolution 7 hex ID as the subdirectory followed by a unique identifier of the station for a Sub sub directory. Which means the link might not work once if the station is moved. But as long as that scenario is handled reasonably gracefully in the explorer if someone uses a link to ask for an H3 cell and station combo that doesn't exist, then such a menu item in the app would be awesome.

Having said all of the above...
The added features, especially a feature to copy all support info to the clipboard so I can paste into Discord, would help me. I've posted 50+ or so GitHub entries. And, I'll possibly post 50+ more eventually. So it would help me. But it would potentially take more time for a developer to code it than the time it will save for me and others that have submitted the majority of the bugs so far. So I suspect the real value would be derived probably not from saving time, but from these 2 things:
1. Ensuring WeatherXM have all the info they need to address an issue and provide support, and
2. Reducing the friction for less involved or less technically capable folks to submit bugs or get technical help. That could widen the circle of folks that provide actionable info that can evolve the deployment side of the project.

**Comment by eeVoskos** [comment]
Ok, so I see two different features here, that both seem very interesting:

### 1. Support requests for a specific station/device

This can be a hidden option in the overflow menu (three dots) of the device detail screen, named "Request support" or "Request help" or sth, and at least as a starting point would pre-populate an email with all required info, including station `name` and `id` (btw the unique station id is the only thing our team needs to start looking into a station issue).

### 2. Share my (public) station url

This could be a "traditional" share button (all platforms have one) that would copy the name of the station and a publicly shareable (explorer) url, e.g. 

> Check out my WeatherXM station 
> Cool Yinmin Smog
> https://explorer.weatherxm.com/#873f3428bffffff/6a2a8870-47d2-11ed-960b-b351f0b0cc44.

We can discuss both with the team and add to our backlog.
