### ISSUE TITLE
Rotate Screen on M5

### ISSUE THREAD

**Issue by Skallagrimmm** [WeatherXM/issue-tracker#28]
### WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this suggestion:
- M5 Firmware

### **Is your feature request related to a problem? Please describe.**

The M5 can only be displayed in one orientation.

### **Describe the solution you'd like**

Add the ability to rotate the screen on the M5 o. Any orientation, this will make it easier to mount in 3rd party/3d printed mounts and will help with cord management.

**Comment by NikosTsiligaridis** [comment]
Rotating the screen 180deg could be added in future versions if it adds to usability, however since its not a critical feature not sure when this will be implemented.
Rotating 90deg on the other hand is a completely different story because horizontal resolution is different from the vertical resolution so the whole UI must be re-adapted for both cases which adds a lot to complexity, not recommended for such a small memory limited device.

Thanks for the suggestion :(

**Comment by Skallagrimmm** [comment]
180⁰ would be great for a little added flexibility and cord management. Understood that it's not a top priority, thanks for the consideration!On Mar. 20, 2022 9:56 a.m., Nikos Tsiligaridis ***@***.***> wrote:
Rotating the screen 180deg could be added in future versions if it adds to usability, however since its not a critical feature not sure when this will be implemented.
Rotating 90deg on the other hand is a completely different story because horizontal resolution is different from the vertical resolution so the whole UI must be re-adapted for both cases which adds a lot to complexity, not recommended for such a small memory limited device.
Thanks for the suggestion :(

**Comment by NikosTsiligaridis** [comment]
Implemented in the latest version, will be released to the public this month.
