### ISSUE TITLE
Explorer wind info showing degrees instead of cardinal/intercardinal directions

### ISSUE THREAD

**Issue by RevNotDev** [WeatherXM/issue-tracker#81]
## WeatherXM Related Element
Please pick one of the following WeatherXM elements that are applicable for this bug:
- Website

## **Describe the bug**
When viewing a station on the Explorer via a web browser, wind is displayed with the speed but then also the direction in degrees straight after without a space in between.

### **How To Reproduce**
Go on https://explorer.weatherxm.com/ and view any station, then look at the wind info.

### **Expected behavior**
The wind info would show as speed and then the cardinal/intercardinal direction with a space in between.

### **Screenshots**
![image](https://user-images.githubusercontent.com/46647866/172701808-bf0b8b90-1694-47e7-9d59-5e2b4cc78320.png)
![image](https://user-images.githubusercontent.com/46647866/172701853-997343ee-36a1-4714-8c0b-e335c3ef0626.png)

### **Additional context**
The bug only shows for me when viewing the explorer on a web browser, but shows correctly through the app.

**Comment by Greg15** [comment]
Rev, in case this is relevant...

The *in-app* explorer has access to our unit preferences we set in the app, so all the units in the in-app explorer display based on our unit preferences as set in the app.
For wind direction, the app supports both degrees and cardinal direction as possible unit preferences.

But the *website* explorer does not have access to our app preferences, so the website explorer uses predefined "standard" units regardless of the viewer. I believe it's "as designed" rather than a bug.

So even though I prefer °F for temp, the website explorer always displays °C. Even though I prefer inches, the website displays mm. Even though I prefer inHg, the website uses hPa.

Same for wind direction. It's degrees instead of cardinal direction. For them to change it, I believe they would need to decide to change the standard for wind direction for everyone.
If they did that, I'm not sure, but that might mean deviating from a standard set of units that are typically used together (kind of like mixing metric and imperial units).

Not sure if there's a way from a person's locale to determine "standard" weather units for the locale, like is done for date formats, etc.

**Comment by RevNotDev** [comment]
I see what you mean Greg. I'd imagine that cardinal directions would suit the majority of users rather than degrees, but like you say, that may have been a conscious decision that's been made. If that's the case then please feel free to delete this bug report. Although at the very least, there should be a space between the speed measurement and the direction, so I could edit this report to reflect only that bug instead if needed.

**Comment by PavlosTze** [comment]
We will look into it and discuss it internally @RevNotDev and @Greg15 . As Greg said we want to use SI units, but I think especially regarding the wind direction we had decided to use cardinal units, I will pass it to the team internally and we will take it from there.

In any case, the space missing is a bug. Thank you!

**Comment by PavlosTze** [comment]
Fixed @Greg15 and @RevNotDev . Added cardinal units and the required space between the units. Thank you for reporting that. I am closing this issue :)
